DjangoEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('allauth.urls')),
    path('', include('core.urls'))
]

core/urls.py
from django.urls import path
from .views import (HomeView, ItemDetailView, CheckoutView, OrderSummaryView,
 PaymentView, add_to_cart, remove_from_cart, remove_single_item_from_cart)

app_name = 'core'

urlpatterns =[
    path('', HomeView.as_view(), name = 'item-list'),
    path('product/<slug>/', ItemDetailView.as_view(), name = 'product'),
    path('checkout/', CheckoutView.as_view(), name = 'checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name = 'order-summary'),
    path('add_to_cart/<slug>',add_to_cart, name = 'add-to-cart'),
    path('remove_from_cart/<slug>', remove_from_cart, name = 'remove-from-cart'),
    path('payment/', PaymentView.as_view(), name = 'payment'),
    path('remove_single_item_from_cart/<slug>', remove_single_item_from_cart, name = 'remove-single-item-from-cart'),

]

core/models.py
from audioop import reverse
from email.policy import default
from secrets import choice
from sre_constants import CATEGORY
from unicodedata import category
from unittest.util import _MAX_LENGTH
from django.db import models
from django.conf import settings
from django.shortcuts import reverse


CATEGORY_CHOICES = (

    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (

    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)



class Item(models.Model):
    title = models.CharField(max_length= 200)
    price = models.FloatField()
    discount_price = models.FloatField(blank = True, null = True)
    category = models.CharField(choices = CATEGORY_CHOICES, max_length = 2)
    label = models.CharField(choices = LABEL_CHOICES, max_length = 1)
    slug = models.SlugField()
    description = models.TextField()
    


    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse("core:product", kwargs = { 'slug': self.slug })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs = { 'slug': self.slug }) 

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs = { 'slug': self.slug })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    ordered= models.BooleanField(default = False)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    quantity = models.IntegerField(default = 1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    ordered= models.BooleanField(default = False)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add = True)
    ordered_date = models.DateTimeField()
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank= True, null = True)
    Payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank= True, null = True)
    
    

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete= models.CASCADE)

    street_address = models.CharField(max_length= 100)
    apartment_address = models.CharField(max_length= 100)
    country = models.CharField(max_length= 100)
    zip = models.CharField(max_length= 100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length= 50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.SET_NULL, blank= True, null= True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.user.username

core/forms.py
from django import forms
#from django_countries.fields import CountryField


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckOutForm(forms.Form):
    street_address = forms.CharField(widget= forms.TextInput(attrs= {
        'placeholder': '1234 main st'
    }))
    apartment_address = forms.CharField(required = False, widget= forms.TextInput(attrs= {
        'placeholder': 'apartment or suite number'
    }))
    #country = CountryField(blank_label = '(select country)')
    zip = forms.CharField()
    same_shipping_address = forms.BooleanField(widget= forms.CheckboxInput())
    save_info = forms.BooleanField(widget= forms.CheckboxInput())
    payment_option = forms.ChoiceField(widget= forms.RadioSelect(), choices = PAYMENT_CHOICES)

core/views.py
#from re import template
from cmath import log
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from django.contrib import messages
from .forms import CheckOutForm
import stripe, logging


stripe.api_key = settings.STRIPE_SECRET_KEY

from .models import Order, Item, OrderItem, BillingAddress, Payment

# class ItemListView(generic.ListView):

#     model = Item
#     context_object_name = 'item_list'
#     queryset = Item.objects.all()
#     template_name = 'core/home-page.html'
#     paginate_by = 5

class CheckoutView(generic.View):
    def get(self, *args, **kwargs):
        form = CheckOutForm()
        context = {
            'form' : form
        }
        return render(self.request, 'core/checkout.html', context)

    def post(self, *args, **kwargs):
        form = CheckOutForm(self.request.POST or None)
        print(self.request.POST)
        try:
            order = Order.objects.get(user = self.request.user, ordered = False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                zip = form.cleaned_data.get("zip")
                country = form.cleaned_data.get('country')
                #same_billing_address = form.cleaned_data.get('same_billing_address')
                #save_info = form.cleaned_data.get('save_info')
                billing_address = BillingAddress(
                    user = self.request.user,
                    street_address = street_address,
                    apartment_address = apartment_address,
                    country = country,
                    zip  = zip

                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                payment_option = form.cleaned_data.get('payment_option') 
                if payment_option == 'S':
                    return redirect('core:payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('core:payment', payment_option='paypal')
                else:
                    messages.warning(self.request, "Invalid payment option selected")
                    return redirect('core:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, 'you do not have any active order.')
            return redirect('core:order-summary')       


class PaymentView(generic.View):
    def get(self, *args, **kwargs):
        return render(self.request, 'core/payment.html')

    def post(self, *args, **kwargs):
        order = Order.objects.get(user = self.request.user, ordered = False)
        token = self.request.POST.get('stripeToken')
        amount = order.get_total() * 100
        
        try:
            charge = stripe.Charge.create(
                amount = amount,
                currency = 'eur',
                source = token
            )
            payment = Payment()
            payment.stripe_charge_id = charge['id']
            payment.user = self.request.user
            payment.amount = amount
            payment.save()

            #assign the payment to order
            order.ordered = True
            order.Payment = payment
            order.save()
            messages.success(self.request, 'your order was successful!')
            return redirect('/')
        except stripe.error.CardError as e:
            logging.error("A payment error occurred: {}".format(e.user_message))
            return redirect('/')
        except stripe.error.InvalidRequestError:
            logging.error("An invalid request occurred.")
            return redirect('/')
        except stripe.error.AuthenticationError:
            logging.error("Not authenticated.")
            return redirect('/')
        except Exception:
            logging.error("Another problem occurred, maybe unrelated to Stripe.")
            return redirect('/')
        

class HomeView(generic.ListView):
    model = Item
    context_object_name = 'item_list'
    queryset = Item.objects.all()
    paginate_by = 10
    template_name = "core/home.html"

class OrderSummaryView(LoginRequiredMixin, generic.View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user = self.request.user, ordered = False)
            context = {
                'object' : order
            }
            return render(self.request, 'core/order_summary.html', context)

        except ObjectDoesNotExist:
            messages.error(self.request, 'you do not have any active order.')
            return redirect('/')
        
    #model = Order
    #template_name = 'home.html'


class ItemDetailView(generic.DetailView):
    model = Item
    context_object_name = 'item_details'
    queryset = Item.objects.all()
    paginate_by = 10
    template_name = "core/product.html"

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug = slug)
    order_item, created = OrderItem.objects.get_or_create(item = item,
    user = request.user,
    ordered = False)
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'this item qunatity is updated.')
            return redirect('core:order-summary')
        else:           
            order.items.add(order_item)
            messages.info(request, 'this item is added to your cart.')
            return redirect('core:order-summary')

    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user = request.user, ordered_date = ordered_date)
        order.items.add(order_item)
        messages.info(request, 'this item qunatity is updated.')
    return redirect('core:order-summary')

@login_required
def remove_from_cart(request, slug):

    item = get_object_or_404(Item, slug = slug)
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item= OrderItem.objects.filter(item = item,
                    user = request.user,
                    ordered = False)[0]
            order.items.remove(order_item)
            messages.info(request, 'this item is removed from your cart.')
            return redirect('core:order-summary')
        else:
            messages.info(request, 'this item is not in your cart.')
            return redirect('core:product',slug = slug)

    else:
        messages.info(request, 'you do not have any active order.')
        return redirect('core:product', slug = slug)


@login_required
def remove_single_item_from_cart(request, slug):

    item = get_object_or_404(Item, slug = slug)
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item= OrderItem.objects.filter(item = item,
                    user = request.user,
                    ordered = False)[0]
            if order_item.quantity >1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, 'this item was updated.')
            return redirect('core:order-summary')
        else:
            messages.info(request, 'this item is not in your cart.')
            return redirect('core:product', slug = slug)

    else:
        messages.info(request, 'you do not have any active order.')
        return redirect('core:product', slug = slug)

core/templates/core/footer.html
<footer class="site-footer border-top">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <p>
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This website is made with <i class="fas fa-heart"></i>
                </p>
            </div>
        </div>
    </div>
</footer>

core/templates/core/home.html
{% extends "account/base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                 <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" 
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

core/templates/core/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

core/templates/core/order_summary.html
{% extends "account/base.html" %}

{% block content %}
  <main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Item Price</th>
                </tr>
                </thead>
                <tbody>
                {% for order_item in object.items.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td><a href = "{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class = 'fas fa-minus mr-2'></i></a>{{ order_item.quantity }}
                        <a href = "{% url 'core:add-to-cart' order_item.item.slug %}"><i class = 'fas fa-plus ml-2'></i></a></td>
                    <td>
                    {% if order_item.item.discount_price %}
                        ${{ order_item.get_total_discount_item_price }}
                        <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved | floatformat:2 }}</span>
                    {% else %}
                        ${{ order_item.get_total_item_price }}
                    {% endif %}
                    <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                        <i class="fas fa-trash float-right"></i>
                    </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan='5'>Your cart is empty</td>
                </tr>
                <tr>
                    <td colspan="5">
                    <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                    </td>
                </tr>
                {% endfor %}
                {% if object.coupon %}
                <tr>
                    <td colspan="4"><b>Coupon</b></td>
                    <td><b>-${{ object.coupon.amount }}</b></td>
                </tr>
                {% endif %}
                {% if object.get_total %}
                <tr>
                    <td colspan="4"><b>Order Total</b></td>
                    <td><b>${{ object.get_total }}</b></td>
                </tr>
                <tr>
                    <td colspan="5">
                    <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                    <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                    </td>
                </tr>
                {% endif %}
                </tbody>
            </table>
        
            </div>    

    </div>
  </main>

{% endblock content %}

core/templates/core/product.html
{% extends "account/base.html" %}
 
{% block content %}
<body>
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

             <!-- {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}  -->

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">
    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

</body>

{% endblock content %}

core/templates/core/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>