DjangoEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('allauth.urls')),
    path('', include('core.urls'))
]

core/urls.py
from django.urls import path
from .views import (HomeView, ItemDetailView, CheckoutView, OrderSummaryView,
 PaymentView, add_to_cart, remove_from_cart, remove_single_item_from_cart)

app_name = 'core'

urlpatterns =[
    path('', HomeView.as_view(), name = 'item-list'),
    path('product/<slug>/', ItemDetailView.as_view(), name = 'product'),
    path('checkout/', CheckoutView.as_view(), name = 'checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name = 'order-summary'),
    path('add_to_cart/<slug>',add_to_cart, name = 'add-to-cart'),
    path('remove_from_cart/<slug>', remove_from_cart, name = 'remove-from-cart'),
    path('payment/', PaymentView.as_view(), name = 'payment'),
    path('remove_single_item_from_cart/<slug>', remove_single_item_from_cart, name = 'remove-single-item-from-cart'),

]

core/models.py
from audioop import reverse
from email.policy import default
from secrets import choice
from sre_constants import CATEGORY
from unicodedata import category
from unittest.util import _MAX_LENGTH
from django.db import models
from django.conf import settings
from django.shortcuts import reverse


CATEGORY_CHOICES = (

    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (

    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)



class Item(models.Model):
    title = models.CharField(max_length= 200)
    price = models.FloatField()
    discount_price = models.FloatField(blank = True, null = True)
    category = models.CharField(choices = CATEGORY_CHOICES, max_length = 2)
    label = models.CharField(choices = LABEL_CHOICES, max_length = 1)
    slug = models.SlugField()
    description = models.TextField()
    


    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse("core:product", kwargs = { 'slug': self.slug })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs = { 'slug': self.slug }) 

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs = { 'slug': self.slug })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    ordered= models.BooleanField(default = False)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    quantity = models.IntegerField(default = 1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    ordered= models.BooleanField(default = False)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add = True)
    ordered_date = models.DateTimeField()
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank= True, null = True)
    Payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank= True, null = True)
    
    

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete= models.CASCADE)

    street_address = models.CharField(max_length= 100)
    apartment_address = models.CharField(max_length= 100)
    country = models.CharField(max_length= 100)
    zip = models.CharField(max_length= 100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length= 50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.SET_NULL, blank= True, null= True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.user.username

core/forms.py
from django import forms
#from django_countries.fields import CountryField


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckOutForm(forms.Form):
    street_address = forms.CharField(widget= forms.TextInput(attrs= {
        'placeholder': '1234 main st'
    }))
    apartment_address = forms.CharField(required = False, widget= forms.TextInput(attrs= {
        'placeholder': 'apartment or suite number'
    }))
    #country = CountryField(blank_label = '(select country)')
    zip = forms.CharField()
    same_shipping_address = forms.BooleanField(widget= forms.CheckboxInput())
    save_info = forms.BooleanField(widget= forms.CheckboxInput())
    payment_option = forms.ChoiceField(widget= forms.RadioSelect(), choices = PAYMENT_CHOICES)

core/views.py
#from re import template
from cmath import log
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from django.contrib import messages
from .forms import CheckOutForm
import stripe, logging


stripe.api_key = settings.STRIPE_SECRET_KEY

from .models import Order, Item, OrderItem, BillingAddress, Payment

# class ItemListView(generic.ListView):

#     model = Item
#     context_object_name = 'item_list'
#     queryset = Item.objects.all()
#     template_name = 'core/home-page.html'
#     paginate_by = 5

class CheckoutView(generic.View):
    def get(self, *args, **kwargs):
        form = CheckOutForm()
        context = {
            'form' : form
        }
        return render(self.request, 'core/checkout.html', context)

    def post(self, *args, **kwargs):
        form = CheckOutForm(self.request.POST or None)
        print(self.request.POST)
        try:
            order = Order.objects.get(user = self.request.user, ordered = False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                zip = form.cleaned_data.get("zip")
                country = form.cleaned_data.get('country')
                #same_billing_address = form.cleaned_data.get('same_billing_address')
                #save_info = form.cleaned_data.get('save_info')
                billing_address = BillingAddress(
                    user = self.request.user,
                    street_address = street_address,
                    apartment_address = apartment_address,
                    country = country,
                    zip  = zip

                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                payment_option = form.cleaned_data.get('payment_option') 
                if payment_option == 'S':
                    return redirect('core:payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('core:payment', payment_option='paypal')
                else:
                    messages.warning(self.request, "Invalid payment option selected")
                    return redirect('core:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, 'you do not have any active order.')
            return redirect('core:order-summary')       


class PaymentView(generic.View):
    def get(self, *args, **kwargs):
        return render(self.request, 'core/payment.html')

    def post(self, *args, **kwargs):
        order = Order.objects.get(user = self.request.user, ordered = False)
        token = self.request.POST.get('stripeToken')
        amount = order.get_total() * 100
        
        try:
            charge = stripe.Charge.create(
                amount = amount,
                currency = 'eur',
                source = token
            )
            payment = Payment()
            payment.stripe_charge_id = charge['id']
            payment.user = self.request.user
            payment.amount = amount
            payment.save()

            #assign the payment to order
            order.ordered = True
            order.Payment = payment
            order.save()
            messages.success(self.request, 'your order was successful!')
            return redirect('/')
        except stripe.error.CardError as e:
            logging.error("A payment error occurred: {}".format(e.user_message))
            return redirect('/')
        except stripe.error.InvalidRequestError:
            logging.error("An invalid request occurred.")
            return redirect('/')
        except stripe.error.AuthenticationError:
            logging.error("Not authenticated.")
            return redirect('/')
        except Exception:
            logging.error("Another problem occurred, maybe unrelated to Stripe.")
            return redirect('/')
        

class HomeView(generic.ListView):
    model = Item
    context_object_name = 'item_list'
    queryset = Item.objects.all()
    paginate_by = 10
    template_name = "core/home.html"

class OrderSummaryView(LoginRequiredMixin, generic.View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user = self.request.user, ordered = False)
            context = {
                'object' : order
            }
            return render(self.request, 'core/order_summary.html', context)

        except ObjectDoesNotExist:
            messages.error(self.request, 'you do not have any active order.')
            return redirect('/')
        
    #model = Order
    #template_name = 'home.html'


class ItemDetailView(generic.DetailView):
    model = Item
    context_object_name = 'item_details'
    queryset = Item.objects.all()
    paginate_by = 10
    template_name = "core/product.html"

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug = slug)
    order_item, created = OrderItem.objects.get_or_create(item = item,
    user = request.user,
    ordered = False)
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'this item qunatity is updated.')
            return redirect('core:order-summary')
        else:           
            order.items.add(order_item)
            messages.info(request, 'this item is added to your cart.')
            return redirect('core:order-summary')

    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user = request.user, ordered_date = ordered_date)
        order.items.add(order_item)
        messages.info(request, 'this item qunatity is updated.')
    return redirect('core:order-summary')

@login_required
def remove_from_cart(request, slug):

    item = get_object_or_404(Item, slug = slug)
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item= OrderItem.objects.filter(item = item,
                    user = request.user,
                    ordered = False)[0]
            order.items.remove(order_item)
            messages.info(request, 'this item is removed from your cart.')
            return redirect('core:order-summary')
        else:
            messages.info(request, 'this item is not in your cart.')
            return redirect('core:product',slug = slug)

    else:
        messages.info(request, 'you do not have any active order.')
        return redirect('core:product', slug = slug)


@login_required
def remove_single_item_from_cart(request, slug):

    item = get_object_or_404(Item, slug = slug)
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item= OrderItem.objects.filter(item = item,
                    user = request.user,
                    ordered = False)[0]
            if order_item.quantity >1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, 'this item was updated.')
            return redirect('core:order-summary')
        else:
            messages.info(request, 'this item is not in your cart.')
            return redirect('core:product', slug = slug)

    else:
        messages.info(request, 'you do not have any active order.')
        return redirect('core:product', slug = slug)

core/templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}
<body>

  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class = 'alert alert-{{ message.tags }} alert-dismissible fade show' role = 'alert'>
          {{ message }}
          <button type = 'button' class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    
        </div>
        {% endfor %}
    {% endif %}
    </div>

    

    {% block content %}
    {% endblock content %}

</body>
</html>

core/templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href = "{% url 'core:item-list' %}" target="_blank">
      <strong class="blue-text">Dj-Ecommerce</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
          Checkout</a>
        </li> {% endcomment %}
      </ul>

   <!-- Right -->
   <ul class="navbar-nav nav-flex-icons">
    {% if request.user.is_authenticated %}
    <li class="nav-item">
      <a href = "{% url 'core:order-summary' %}" class="nav-link waves-effect">
        <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
        <i class="fas fa-shopping-cart"></i>
        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
        <span class="clearfix d-none d-sm-inline-block"> Logout </span>
      </a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link waves-effect" href="{% url 'account_login' %}">
        <span class="clearfix d-none d-sm-inline-block"> Login </span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
        <span class="clearfix d-none d-sm-inline-block"> Signup </span>
      </a>
    </li>
    {% endif %}
  </ul>

    </div>

  </div>
</nav>